import { GridFSBucket, MongoClient, ObjectId } from "mongodb";
import { ENV } from "./env.js";

export type Asset = { id: number; kind: "file" | "config"; title: string; category: string; fileName?: string | null; mimeType?: string | null; storageKey?: string | null; contentText?: string | null; sizeBytes?: number | null; published: number; createdAt: Date; updatedAt: Date };
export type Service = { id: number; title: string; category: string; description: string; url?: string | null; published: number; createdAt: Date; updatedAt: Date };
let client: MongoClient | undefined; let db: ReturnType<MongoClient["db"]> | undefined; let bucket: GridFSBucket | undefined;
export async function getMongo() { if (!ENV.mongodbUri) throw new Error("MONGODB_URI is not configured"); if (!client) { client = new MongoClient(ENV.mongodbUri, { tls: true, family: 4, serverSelectionTimeoutMS: 8000, connectTimeoutMS: 8000 }); await client.connect(); db = client.db(ENV.mongodbDatabase); bucket = new GridFSBucket(db, { bucketName: "files" }); } return { db: db!, bucket: bucket! }; }
async function nextId(name: string) { const { db } = await getMongo(); const result = await db.collection<{ _id: string; value: number }>("counters").findOneAndUpdate({ _id: name }, { $inc: { value: 1 } }, { upsert: true, returnDocument: "after" }); return result!.value; }
export async function upsertTelegramSubscriber(input: { telegramUserId: string; username?: string; firstName?: string }) { const { db } = await getMongo(); await db.collection("telegramSubscribers").updateOne({ telegramUserId: input.telegramUserId }, { $set: { username: input.username ?? null, firstName: input.firstName ?? null, lastSeenAt: new Date() } }, { upsert: true }); }
export async function listAssets(includeUnpublished = false) { const { db } = await getMongo(); return db.collection<Asset>("assets").find(includeUnpublished ? {} : { published: 1 }).sort({ createdAt: -1 }).toArray(); }
export async function getAsset(id: number) { const { db } = await getMongo(); return db.collection<Asset>("assets").findOne({ id }); }
export async function createAsset(input: Omit<Asset, "id" | "createdAt" | "updatedAt">) { const { db } = await getMongo(); const now = new Date(); const asset = { ...input, id: await nextId("assets"), createdAt: now, updatedAt: now }; await db.collection<Asset>("assets").insertOne(asset); return asset.id; }
export async function listServices(includeUnpublished = false) { const { db } = await getMongo(); return db.collection<Service>("services").find(includeUnpublished ? {} : { published: 1 }).sort({ createdAt: -1 }).toArray(); }
export async function createService(input: Omit<Service, "id" | "createdAt" | "updatedAt">) { const { db } = await getMongo(); const now = new Date(); const service = { ...input, id: await nextId("services"), createdAt: now, updatedAt: now }; await db.collection<Service>("services").insertOne(service); return service.id; }
export async function setAssetPublished(id: number, published: boolean) { const { db } = await getMongo(); await db.collection("assets").updateOne({ id }, { $set: { published: published ? 1 : 0, updatedAt: new Date() } }); }
export async function storeFile(filename: string, data: Buffer, contentType: string) { const { bucket } = await getMongo(); const upload = bucket.openUploadStream(filename, { metadata: { contentType } }); await new Promise<void>((resolve, reject) => { upload.once("finish", () => resolve()); upload.once("error", reject); upload.end(data); }); return String(upload.id); }
export async function readFile(storageKey: string) { const { bucket } = await getMongo(); const chunks: Buffer[] = []; await new Promise<void>((resolve, reject) => { const stream = bucket.openDownloadStream(new ObjectId(storageKey)); stream.on("data", chunk => chunks.push(Buffer.from(chunk))); stream.once("end", () => resolve()); stream.once("error", reject); }); return Buffer.concat(chunks); }
