import { ENV } from "./env.js";

type PaymentStatus = { status?: string; mpesaReceipt?: string | null; resultDesc?: string; amountKes?: number; transactionId?: string; final?: boolean };
export function extractCheckoutId(value: Record<string, unknown>) { const id = value.checkoutRequestId ?? value.CheckoutRequestID ?? value.checkoutRequestID ?? value.checkoutRequestId ?? value.checkout_request_id ?? value.requestId ?? value.requestID; return typeof id === "string" || typeof id === "number" ? String(id).trim() : ""; }
function headers() { if (!ENV.leetecApiKey) throw new Error("LEETEC_API_KEY is not configured"); return { Authorization: `Bearer ${ENV.leetecApiKey}`, "Content-Type": "application/json" }; }
async function call(path: string, body: unknown) { const response = await fetch(`${ENV.leetecBaseUrl}${path}`, { method: "POST", headers: headers(), body: JSON.stringify(body) }); const data = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(data.error ?? data.message ?? `LeeTec request failed (${response.status})`)); return data; }
export async function startPayment(phone: string, amount: number, reference: string, _chatId: number) { const body: Record<string, unknown> = { phoneNumber: phone, amount, accountReference: reference.startsWith("1") ? reference.slice(0, 64) : `1${reference}`.slice(0, 64), transactionDesc: "LEETECH VPN subscription" }; if (ENV.leetecTillId) body.tillId = ENV.leetecTillId; return call("/api/v1/stkpush", body); }
export async function checkPayment(checkoutRequestId: string) { const wanted = checkoutRequestId.trim(); if (ENV.leetecStatusUrl) { const url = ENV.leetecStatusUrl.replace("{id}", encodeURIComponent(wanted)); const response = await fetch(url, { method: "GET", headers: headers() }); const data = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(data.error ?? data.message ?? `LeeTec status request failed (${response.status})`)); return normalizeStatus(data); } const paths = ["/api/v1/transactions", "/api/v1/stkpush/history", "/api/v1/collections"]; let lastError = ""; for (const path of paths) { const response = await fetch(`${ENV.leetecBaseUrl}${path}`, { method: "GET", headers: headers() }); const data = await response.json() as Record<string, unknown>; if (!response.ok) { lastError = String(data.error ?? data.message ?? `LeeTec history request failed (${response.status})`); continue; } const rows = collectRows(data); const match = rows.find(row => extractCheckoutId(row) === wanted); if (match) return normalizeStatus(match); } return { status: "PENDING", resultDesc: lastError || "Waiting for LeeTec to record the payment." } as PaymentStatus; }
function collectRows(data: Record<string, unknown> | unknown): Record<string, unknown>[] { if (Array.isArray(data)) return data.filter(row => row && typeof row === "object") as Record<string, unknown>[]; if (!data || typeof data !== "object") return []; const object = data as Record<string, unknown>; for (const key of ["data", "transactions", "collections", "results", "items"]) { const value = object[key]; if (Array.isArray(value)) return value.filter(row => row && typeof row === "object") as Record<string, unknown>[]; if (value && typeof value === "object") { const nested = collectRows(value); if (nested.length) return nested; } } return []; }
function normalizeStatus(data: Record<string, unknown>): PaymentStatus { return { status: String(data.status ?? data.paymentStatus ?? data.result ?? "PENDING").toUpperCase(), mpesaReceipt: data.mpesaReceipt ?? data.MpesaReceiptNumber ?? data.receipt ? String(data.mpesaReceipt ?? data.MpesaReceiptNumber ?? data.receipt) : null, resultDesc: String(data.resultDesc ?? data.message ?? data.description ?? ""), transactionId: String(data.transactionId ?? data.id ?? ""), final: data.final === true || ["SUCCESS", "FAILED", "CANCELLED", "ERROR"].includes(String(data.status ?? "").toUpperCase()) }; }
