import type { Express } from "express";
import { createHash } from "node:crypto";
import { createAsset, createService, getAsset, listAssets, listServices, readFile, storeFile, upsertTelegramSubscriber } from "./db.js";
import { ENV, missingEnv } from "./env.js";
import { checkPayment, startPayment } from "./courtney.js";

type User = { id: number; username?: string; first_name?: string }; type Message = { chat: { id: number }; message_id?: number; from?: User; text?: string; caption?: string; document?: { file_id: string; file_name?: string; mime_type?: string; file_size?: number } }; type Update = { message?: Message; callback_query?: { id: string; data?: string; from: User; message?: Message } }; type Keyboard = { inline_keyboard: { text: string; callback_data: string }[][] }; type ApiResponse<T> = { ok: boolean; result?: T; description?: string };
const uploadMode = new Set<string>();
function requireTelegram() { if (!ENV.telegramBotToken) throw new Error("TELEGRAM_BOT_TOKEN is not configured"); return ENV.telegramBotToken; }
function secret() { return createHash("sha256").update(requireTelegram()).digest("hex").slice(0, 48); }
async function api<T>(method: string, body: Record<string, unknown>) { const response = await fetch(`https://api.telegram.org/bot${requireTelegram()}/${method}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as ApiResponse<T>; if (!response.ok || !payload.ok) throw new Error(payload.description ?? `${method} failed`); return payload.result as T; }
const send = (chatId: number, text: string, reply_markup?: Keyboard) => api("sendMessage", { chat_id: chatId, text, disable_web_page_preview: true, reply_markup });
const edit = (chatId: number, messageId: number, text: string, reply_markup?: Keyboard) => api("editMessageText", { chat_id: chatId, message_id: messageId, text, disable_web_page_preview: true, reply_markup });
const admin = (user?: User) => Boolean(user && String(user.id) === ENV.telegramAdminUserId);
const menu = (isAdmin = false): Keyboard => ({ inline_keyboard: [[{ text: "📦 Files", callback_data: "files" }, { text: "🛠 Services", callback_data: "services" }], [{ text: "💳 Pay M-Pesa", callback_data: "payhelp" }], ...(isAdmin ? [[{ text: "⬆️ Upload", callback_data: "upload" }, { text: "⚙️ Admin help", callback_data: "adminhelp" }]] : [])] });
const back = (isAdmin = false): Keyboard => ({ inline_keyboard: [[{ text: "⬅️ Menu", callback_data: "home" }], ...(isAdmin ? [[{ text: "⬆️ Upload", callback_data: "upload" }]] : [])] });
function assetText(items: Awaited<ReturnType<typeof listAssets>>) { return items.length ? items.map((a, i) => `${i + 1}. ${a.title} · ${a.category} [${a.kind}]`).join("\n") : "No published files or configs yet."; }
function serviceText(items: Awaited<ReturnType<typeof listServices>>) { return items.length ? items.map(s => `${s.title} · ${s.category}\n${s.description}${s.url ? `\n${s.url}` : ""}`).join("\n\n") : "No published services yet."; }
async function sendAsset(chatId: number, id: number) { const asset = await getAsset(id); if (!asset || asset.published !== 1) return; if (asset.kind === "config") return send(chatId, `${asset.title} · ${asset.category}\n\n${(asset.contentText ?? "").slice(0, 3800)}`); if (asset.storageKey) { const data = await readFile(asset.storageKey); const form = new FormData(); form.append("chat_id", String(chatId)); form.append("caption", `${asset.title} · ${asset.category}`); form.append("document", new Blob([data], { type: asset.mimeType ?? "application/octet-stream" }), asset.fileName ?? "file"); await fetch(`https://api.telegram.org/bot${requireTelegram()}/sendDocument`, { method: "POST", body: form }); } }
async function sendFiles(chatId: number, isAdmin: boolean) { const assets = await listAssets(); await send(chatId, `📦 Files & configs\n\n${assetText(assets)}`, back(isAdmin)); for (const asset of assets) await sendAsset(chatId, asset.id); }
async function handleDocument(message: Message) { if (!message.document || !admin(message.from)) return; const key = String(message.from!.id); const caption = message.caption?.trim() ?? ""; if (!uploadMode.has(key) && !caption.toLowerCase().startsWith("/add")) return; if ((message.document.file_size ?? 0) > 20 * 1024 * 1024) return send(message.chat.id, "Files must be 20 MB or smaller."); const file = await api<{ file_path?: string }>("getFile", { file_id: message.document.file_id }); if (!file.file_path) throw new Error("Telegram file path missing"); const response = await fetch(`https://api.telegram.org/file/bot${requireTelegram()}/${file.file_path}`); const data = Buffer.from(await response.arrayBuffer()); const header = caption.replace(/^\/add\s*/i, ""); const [categoryPart, titlePart] = header.split("|").map(x => x.trim()); const category = titlePart ? categoryPart || "General" : "General"; const title = (titlePart || categoryPart || message.document.file_name || "Shared file").trim(); const storageKey = await storeFile(message.document.file_name ?? title, data, message.document.mime_type ?? "application/octet-stream"); const id = await createAsset({ kind: "file", title, category, fileName: message.document.file_name ?? null, mimeType: message.document.mime_type ?? null, storageKey, sizeBytes: data.length, published: 1 }); await send(message.chat.id, `✅ Uploaded #${id}: ${title}`, { inline_keyboard: [[{ text: "✅ Done", callback_data: "done" }]] }); }
async function handleAdmin(message: Message, text: string) { const [command, ...rest] = text.trim().split(/\s+/); const arg = rest.join(" ").trim(); if (command === "/upload") { uploadMode.add(String(message.from!.id)); return send(message.chat.id, "Upload mode active. Send files with caption `Category | Title`, then tap Done.", { inline_keyboard: [[{ text: "✅ Done", callback_data: "done" }]] }); } if (command === "/service") { const p = arg.split("|").map(x => x.trim()); if (p.length < 3) return send(message.chat.id, "Usage: /service Title | Category | Description | URL"); await createService({ title: p[0], category: p[1], description: p[2], url: p[3] || null, published: 1 }); return send(message.chat.id, "✅ Service published", menu(true)); } if (command === "/addconfig") { const n = arg.indexOf("\n"); if (n < 1) return send(message.chat.id, "Usage: /addconfig Category | Title then a new line with config text"); const [category, title] = arg.slice(0, n).split("|").map(x => x.trim()); await createAsset({ kind: "config", title: title || category, category: title ? category : "General", contentText: arg.slice(n + 1).trim(), published: 1 }); return send(message.chat.id, "✅ Config published", menu(true)); } if (command === "/pay") { const [phone, amountText] = arg.split(/\s+/); const amount = Number(amountText); if (!phone || !Number.isInteger(amount) || amount < 1) return send(message.chat.id, "Usage: /pay 0712345678 500"); const ref = `VPN${Date.now().toString().slice(-9)}`; const result = await startPayment(phone, amount, ref, message.chat.id); return send(message.chat.id, `📲 STK Push sent for KES ${amount}.\nCheckout ID: ${String(result.checkoutRequestId ?? result.checkout_request_id ?? "unknown")}\nUse /paystatus CHECKOUT_ID to check payment.`); } if (command === "/paystatus") { if (!arg) return send(message.chat.id, "Usage: /paystatus CHECKOUT_ID"); const result = await checkPayment(arg); return send(message.chat.id, `Payment status: ${result.status ?? "unknown"}${result.mpesaReceipt ? `\nReceipt: ${result.mpesaReceipt}` : ""}${result.resultDesc ? `\n${result.resultDesc}` : ""}`); } }
async function callback(update: Update["callback_query"]) { if (!update?.message) return; await api("answerCallbackQuery", { callback_query_id: update.id }); const chat = update.message.chat.id; const messageId = update.message.message_id; if (!messageId) return; const isAdmin = admin(update.from); if (update.data === "home") return edit(chat, messageId, "LEETECH VPN BOT\n\nChoose an option:", menu(isAdmin)); if (update.data === "files") return edit(chat, messageId, `📦 Files & configs\n\n${assetText(await listAssets())}`, back(isAdmin)); if (update.data === "services") return edit(chat, messageId, `🛠 Services\n\n${serviceText(await listServices())}`, back(isAdmin)); if (update.data === "payhelp") return edit(chat, messageId, "💳 M-Pesa payment\n\nSend /pay 0712345678 500 to receive an STK Push.", back(isAdmin)); if (update.data === "upload" && isAdmin) { uploadMode.add(String(update.from.id)); return edit(chat, messageId, "Upload mode active. Send files with caption `Category | Title`, then tap Done.", { inline_keyboard: [[{ text: "✅ Done", callback_data: "done" }]] }); } if (update.data === "done" && isAdmin) { uploadMode.delete(String(update.from.id)); return edit(chat, messageId, "Upload mode finished.", menu(true)); } if (update.data === "adminhelp" && isAdmin) return edit(chat, messageId, "Admin commands:\n/upload\n/addconfig Category | Title then config text\n/service Title | Category | Description | URL\n/pay phone amount", back(true)); }
export async function processTelegramUpdate(update: Update) { const message = update.message; try { if (update.callback_query) return callback(update.callback_query); if (!message) return; if (message.from) await upsertTelegramSubscriber({ telegramUserId: String(message.from.id), username: message.from.username, firstName: message.from.first_name }); if (message.document) return handleDocument(message); const text = message.text?.trim() ?? ""; if (["/start", "/menu", "/help"].includes(text)) return send(message.chat.id, "LEETECH VPN BOT\n\nChoose an option:", menu(admin(message.from))); if (text === "/files") return sendFiles(message.chat.id, admin(message.from)); if (text === "/services") return send(message.chat.id, serviceText(await listServices()), back(admin(message.from))); if (admin(message.from) && text.startsWith("/")) return handleAdmin(message, text); } catch (error) { console.error("[Telegram] update failed", error); if (update.message?.chat.id) await send(update.message.chat.id, "Something went wrong. Please try again.").catch(() => undefined); } }
export function registerTelegramRoutes(app: Express) { app.post("/api/telegram/webhook", (req, res) => { if (req.header("x-telegram-bot-api-secret-token") !== secret()) return res.status(403).json({ ok: false }); res.status(200).json({ ok: true }); void processTelegramUpdate(req.body as Update); }); app.get("/api/health", (_req, res) => res.json({ ok: missingEnv().length === 0, missing: missingEnv() })); }
export async function configureTelegram() {
  if (!ENV.publicAppUrl || !ENV.telegramBotToken) return;
  await api("setMyCommands", { commands: [{ command: "start", description: "Open the menu" }, { command: "files", description: "Browse files and configs" }, { command: "services", description: "Browse services" }, { command: "pay", description: "Start an M-Pesa payment" }, { command: "upload", description: "Admin: upload files" }] });
  await api("setWebhook", { url: `${ENV.publicAppUrl}/api/telegram/webhook`, secret_token: secret(), drop_pending_updates: false });
}
export function webhookSecret() { return secret(); }
